# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3befd2d55ea47d795568c1fec9c16485b6ffa30e8b8761ffc2fbf010b598e153039e71e00e2df1f964ea97cccade43f45b93907f4a8d5eae06bd479e9061f90d

test:
  secret_key_base: 8ec8a68ddb43e52c07b31e6c12966ca3b9689194e611e6ed197653851af49452cdfadfa69bcce6ba4338132744219353c4cb6147f66b1b9907e4bb7223e8742b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
